<?php

namespace Lucius\ShineMonitorApi\Enums;

enum ShineMonitorErrorCode: int
{
    case ERR_NONE = 0x0000;
    case ERR_FAIL = 0x0001;
    case ERR_TIMEOUT = 0x0002;
    case ERR_SYSTEM_EXCEPTION = 0x0003;
    case ERR_SIGN = 0x0004;
    case ERR_SALT = 0x0005;
    case ERR_FORMAT_ERROR = 0x0006;
    case ERR_MISSING_PARAMETER = 0x0007;
    case ERR_FORBIDDEN = 0x0008;
    case ERR_UNSUPPORTED = 0x0009;
    case ERR_NO_AUTH = 0x000A;
    case ERR_NO_PERMISSION = 0x000B;
    case ERR_NO_RECORD = 0x000C;
    case ERR_OVER_LIMITED = 0x000D;
    case ERR_DUPLICATE_OPER = 0x000E;
    case ERR_NOT_FOUND_COMPANY_KEY = 0x000F;
    case ERR_PASSWORD_VERIF_FAIL = 0x0010;
    case ERR_PASSWORD_FORMAT_ERROR = 0x0011;
    case ERR_MOBILE_BINDED = 0x0012;
    case ERR_MOBILE_FORMAT = 0x0013;
    case ERR_EMAIL_FORMAT = 0x0014;
    case ERR_USRNAME_FORMAT = 0x0015;
    case ERR_COMPANY_NAME_FORMAT = 0x0016;
    case ERR_VCODE_INVALID = 0x0017;
    case ERR_USR_NAME_DUPLICATE = 0x0018;
    case ERR_USR_DISABLED = 0x0019;
    case ERR_NOT_FOUND_API = 0x0100;
    case ERR_NOT_FOUND_COLLECTOR = 0x0101;
    case ERR_NOT_FOUND_DEVICE = 0x0102;
    case ERR_INVALID_PN = 0x0103;
    case ERR_NOT_FOUND_PLANT = 0x0104;
    case ERR_NOT_FOUND_USR = 0x0105;
    case ERR_DEVICE_OFFLINE = 0x0106;
    case ERR_COLLECTOR_OFFLINE = 0x0107;
    case ERR_NOT_FOUND_DEVICE_WARNING = 0x0108;
    case ERR_NOT_FOUND_ENVMONITOR = 0x0109;
    case ERR_NONE_OPERATION = 0x010F;
    case ERR_DUPLICATE_OPER_BIND = 0x0110;
    case ERR_NOT_SUPPORT_ADD_OTHER_VCODE_COLLECTOR = 0x0111;
    case ERR_USR_BIND_WX_BIND = 0x0112;
    case ERR_NOT_BIND_WX = 0x0113;
    case ERR_NOT_SUPPORT_MOVE_OTHER_VCODE_COLLECTOR_PLANTOWNER = 0x0114;
    case ERR_NOT_FOUND_VENDOR = 0x0115;
    case ERR_NOT_FOUND_CAMERA = 0x0120;
    case ERR_NOT_FOUND_FIREWARE = 0x0160;
    case ERR_NOT_FOUND_PROTOCOL = 0x0161;
    case ERR_NOT_FOUND_DEFINEDROLE = 0x0170;
    case ERR_NOT_FOUND_USR_GROUP = 0x0171;
    case ERR_NOT_FOUND_PLANT_GROUP = 0x0172;
    case ERR_NOT_FOUND_GPRS_TARIFFPACKAGE = 0x0173;
    case ERR_NOT_FOUND_RECHARGE_ORDER = 0x0174;
    case ERR_NOT_FOUND_SMSCODE = 0x0180;
    case ERR_NOT_FOUND_DEVICE_TOKEN = 0x0181;
    case ERR_NOT_FOUND_DEVICE_CFG = 0x0182;
    case ERR_NOT_FOUND_COLLECTOR_TYPE = 0x0183;
    case ERR_NOT_FOUND_PERMISSION_GROUP = 0x0184;
    case ERR_NOT_SETTING_LONLAT = 0x0185;
    case ERR_SMSCODE_DISMATCH = 0x0200;
    case ERR_SMSCODE_OVERTIME = 0x0201;
    case ERR_MOBILE_UNBINDED = 0x0202;
    case ERR_MOBILE_UNMATCH = 0x0203;
    case ERR_NAME_DUPLICATE = 0x0204;
    case ERR_COLLECOTR_ISNOT_EMPTY = 0x0205;
    case ERR_SUBUSR_ISNOT_EMPTY = 0x0206;
    case ERR_USR_EXISTED = 0x0207;
    case ERR_PN_REGISTER = 0x0208;
    case ERR_COLLECTOR_NOTBELONG_USR = 0x0209;
    case ERR_COLLECTOR_EXISTED = 0x020A;
    case ERR_NOT_PLANTBROWSER = 0x020B;
    case ERR_SMSCODE_TO_SHORT = 0x020C;
    case ERR_PROTOCOL_NOT_OPTION = 0x0300;
    case ERR_OLNY_SUPPORT_PLANTOWNER = 0x0400;
    case ERR_OLNY_SUPPORT_DIST = 0x0401;
    case ERR_OLNY_SUPPORT_VERDOR = 0x0402;
    case ERR_SUPERIOR_DIST_VERDOR = 0x0403;
    case ERR_UNSUPPORTED_CHARGE_TYPE = 0x0404;
    case ERR_DUPLICATE_PN = 0x0405;
    case ERR_INVALID_GPRS_CARD = 0x0406;
    case ERR_USR_NOT_CREATE_ADMIN = 0x0407;
    case ERR_SUPPORT_DIST_VERDOR = 0x0408;
    case ERR_NOT_CONFIRM = 0x0409;
    case ERR_ACCEPT = 0x0410;
    case ERR_QR_KEY_INVALID = 0x0411;
    case ERR_INVALID_CCID = 0x0412;
    case ERR_COLLECTORS_NOT_ONLY_BELONG_DIST = 0x0700;

    public function description()
    {
        return match ($this) {
            self::ERR_NONE => 'OK. Sem Erros',
            self::ERR_FAIL => 'Falha',
            self::ERR_TIMEOUT => 'Tempo esgotado',
            self::ERR_SYSTEM_EXCEPTION => 'Exceção do sistema',
            self::ERR_SIGN => 'Assinatura não verificável',
            self::ERR_SALT => 'Valor de salt errado, não usado de acordo com as regras',
            self::ERR_FORMAT_ERROR => 'Erro de formato de parâmetro',
            self::ERR_MISSING_PARAMETER => 'Parâmetro obrigatório ausente',
            self::ERR_FORBIDDEN => 'Rejeição da plataforma',
            self::ERR_UNSUPPORTED => 'Operação sem suporte',
            self::ERR_NO_AUTH => 'Não certificado',
            self::ERR_NO_PERMISSION => 'Operação não autorizada',
            self::ERR_NO_RECORD => 'Sem registro',
            self::ERR_OVER_LIMITED => 'Limite excedido',
            self::ERR_DUPLICATE_OPER => 'Operações repetidas',
            self::ERR_NOT_FOUND_COMPANY_KEY => 'Chave do fabricante não encontrada',
            self::ERR_PASSWORD_VERIF_FAIL => 'A verificação da senha falhou',
            self::ERR_PASSWORD_FORMAT_ERROR => 'Formato de senha errado',
            self::ERR_MOBILE_BINDED => 'O número do celular está vinculado',
            self::ERR_MOBILE_FORMAT => 'Formato de número de telefone incorreto',
            self::ERR_EMAIL_FORMAT => 'Erro de formato de email',
            self::ERR_USRNAME_FORMAT => 'Erro de formato de nome de usuário',
            self::ERR_COMPANY_NAME_FORMAT => 'Erro no formato do nome da empresa',
            self::ERR_VCODE_INVALID => 'Código do fabricante inválido',
            self::ERR_USR_NAME_DUPLICATE => 'Nome de usuário duplicado',
            self::ERR_USR_DISABLED => 'A conta está congelada',
            self::ERR_NOT_FOUND_API => 'Não foi possível encontrar a API para chamar',
            self::ERR_NOT_FOUND_COLLECTOR => 'Não é possível encontrar o registrador',
            self::ERR_NOT_FOUND_DEVICE => 'Dispositivo não encontrado',
            self::ERR_INVALID_PN => 'Número de registrador inválido',
            self::ERR_NOT_FOUND_PLANT => 'Não é possível encontrar a estação de energia',
            self::ERR_NOT_FOUND_USR => 'Usuário não encontrado',
            self::ERR_DEVICE_OFFLINE => 'O dispositivo está off-line',
            self::ERR_COLLECTOR_OFFLINE => 'O registrador está offline',
            self::ERR_NOT_FOUND_DEVICE_WARNING => 'Aviso de dispositivo não encontrado',
            self::ERR_NOT_FOUND_ENVMONITOR => 'Não é possível encontrar o detector de ambiente',
            self::ERR_NONE_OPERATION => 'Nenhuma modificação',
            self::ERR_DUPLICATE_OPER_BIND => 'Repetir encadernação',
            self::ERR_NOT_SUPPORT_ADD_OTHER_VCODE_COLLECTOR => 'Não suporta adicionar coletores de dados de outros fabricantes',
            self::ERR_USR_BIND_WX_BIND => 'A conta foi vinculada ao WeChat',
            self::ERR_NOT_BIND_WX => 'A conta não está vinculada ao WeChat',
            self::ERR_NOT_SUPPORT_MOVE_OTHER_VCODE_COLLECTOR_PLANTOWNER => 'Não há suporte para mover proprietários de usinas que contenham coletores de dados de outros fabricantes',
            self::ERR_NOT_FOUND_VENDOR => 'Não consigo encontrar o fabricante',
            self::ERR_NOT_FOUND_CAMERA => 'Câmera não encontrada',
            self::ERR_NOT_FOUND_FIREWARE => 'Firmware não encontrado',
            self::ERR_NOT_FOUND_PROTOCOL => 'Acordo não encontrado',
            self::ERR_NOT_FOUND_DEFINEDROLE => 'Não é possível encontrar o personagem',
            self::ERR_NOT_FOUND_USR_GROUP => 'Não é possível encontrar o grupo de usuários',
            self::ERR_NOT_FOUND_PLANT_GROUP => 'Não foi possível encontrar o grupo de plantas',
            self::ERR_NOT_FOUND_GPRS_TARIFFPACKAGE => 'Não é possível encontrar o pacote de recarga de tráfego GPRS',
            self::ERR_NOT_FOUND_RECHARGE_ORDER => 'Não é possível encontrar o pedido de recarga de tráfego GPRS',
            self::ERR_NOT_FOUND_SMSCODE => 'Não é possível encontrar o código de verificação por SMS',
            self::ERR_NOT_FOUND_DEVICE_TOKEN => 'Device_token não encontrado',
            self::ERR_NOT_FOUND_DEVICE_CFG => 'Informações de configuração do dispositivo não encontradas',
            self::ERR_NOT_FOUND_COLLECTOR_TYPE => 'Não é possível encontrar o tipo de registrador',
            self::ERR_NOT_FOUND_PERMISSION_GROUP => 'Não foi possível encontrar o grupo de permissão',
            self::ERR_NOT_SETTING_LONLAT => 'Latitude e longitude não definidas',
            self::ERR_SMSCODE_DISMATCH => 'O código de verificação por SMS não corresponde',
            self::ERR_SMSCODE_OVERTIME => 'O código de verificação por SMS expirou',
            self::ERR_MOBILE_UNBINDED => 'O número de telefone não está vinculado',
            self::ERR_MOBILE_UNMATCH => 'Os números de telefone não correspondem',
            self::ERR_NAME_DUPLICATE => 'Os nomes não podem ser iguais',
            self::ERR_COLLECOTR_ISNOT_EMPTY => 'Existem também coletores de dados sob o usuário ou estação de energia',
            self::ERR_SUBUSR_ISNOT_EMPTY => 'O usuário também tem usuários subordinados',
            self::ERR_USR_EXISTED => 'Usuário já existe',
            self::ERR_PN_REGISTER => 'O número do registrador foi registrado',
            self::ERR_COLLECTOR_NOTBELONG_USR => 'O registrador de dados não pertence a este usuário',
            self::ERR_COLLECTOR_EXISTED => 'O registrador já existe',
            self::ERR_NOT_PLANTBROWSER => 'Não é uma conta de visualizador',
            self::ERR_SMSCODE_TO_SHORT => 'O tempo de envio do código de verificação por SMS é muito curto',
            self::ERR_PROTOCOL_NOT_OPTION => 'Não há campos opcionais no protocolo',
            self::ERR_OLNY_SUPPORT_PLANTOWNER => 'Apoie apenas proprietários de usinas',
            self::ERR_OLNY_SUPPORT_DIST => 'Suporte apenas a revendedores',
            self::ERR_OLNY_SUPPORT_VERDOR => 'Oferece suporte apenas a fabricantes de dispositivos',
            self::ERR_SUPERIOR_DIST_VERDOR => 'O usuário superior precisa ser um revendedor ou fabricante de equipamentos',
            self::ERR_UNSUPPORTED_CHARGE_TYPE => 'Método de recarga não compatível',
            self::ERR_DUPLICATE_PN => 'Número do registrador duplicado',
            self::ERR_INVALID_GPRS_CARD => 'Cartão GPRS inválido',
            self::ERR_USR_NOT_CREATE_ADMIN => 'Usuário não criado pelo administrador',
            self::ERR_SUPPORT_DIST_VERDOR => 'Suporta apenas contas de fábrica e revendedores',
            self::ERR_NOT_CONFIRM => 'Ainda não escaneado',
            self::ERR_ACCEPT => 'Digitalizado, não confirmado',
            self::ERR_QR_KEY_INVALID => 'A chave expirou ou não pode ser encontrada',
            self::ERR_INVALID_CCID => 'CCID inválido',
            self::ERR_COLLECTORS_NOT_ONLY_BELONG_DIST => 'Os madeireiros devem todos pertencer ao distribuidor',
        };
    }
}
